version: '3.1'
services:
  app-jvm:
    container_name: app-jvm
    image: ivanklp/image-jvm
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jugmadrid-db:5432/jug-madrid
      - SPRING_LIQUIBASE_ENABLED=false
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
      - MANAGEMENT_METRICS_TAGS_APPLICATION=jvm
    ports:
      - "8080:8080"
    depends_on:
      - db
  app-native:
    container_name: app-native
    image: ivanklp/image-native
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://jugmadrid-db:5432/jug-madrid
      #- SPRING_LIQUIBASE_ENABLED=false
      - SERVER_PORT=8081
      - MANAGEMENT_ZIPKIN_TRACING_ENDPOINT=http://tempo:9411/api/v2/spans
      - MANAGEMENT_METRICS_TAGS_APPLICATION=native
    ports:
      - "8081:8081"
    depends_on:
      - db
  db:
    container_name: jugmadrid-db
    image: postgres:15.1
    volumes:
      - sample_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=jug-madrid
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    extra_hosts: ['host.docker.internal:host-gateway']
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./etc/prometheus/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    extra_hosts: ['host.docker.internal:host-gateway']
    volumes:
      - ./etc/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources:ro
      - ./etc/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
  tempo:
    image: grafana/tempo
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./etc/tempo/tempo-local.yaml:/etc/tempo.yaml:ro
      - ./tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin
  loki:
    image: grafana/loki
    extra_hosts: ['host.docker.internal:host-gateway']
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
volumes:
  sample_db: {}